version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

workflows:
  version: 2
  workflow:
    jobs:

      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - diff_aws:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^v\d+\.\d+\.\d+$/

      - deploy_aws:
          requires: [ 'test' ]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - deploy_npm:
          requires: [
            'test',
            'deploy_aws'
          ]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

commands:

  aws-configure-role-profile:
    parameters:
      role_arn:
        type: string
    steps:
      - aws-cli/setup: { profile-name: build_user }
      - run:
          name: "Configure AWS Default Profile"
          command: >
            aws configure set role_arn "<<parameters.role_arn>>" --profile default;
            aws configure set source_profile build_user --profile default

jobs:

  test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout

      - run:
         name: npm install
         command: npm install

      - run:
         name: npm run ci
         command: npm run ci

  diff_aws:
    executor: aws-cli/default
    environment:
       AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/install

      - aws-configure-role-profile:
         role_arn: "arn:aws:iam::378118068829:role/schemas-publisher"

      - run:
         name: aws s3 sync --dryrun
         command: aws s3 sync --dryrun --profile default --size-only ./schemas/ s3://schemas.dev.brightspace.com/feature-flags/

  deploy_aws:
    executor: aws-cli/default
    environment:
       AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - aws-cli/install

      - aws-configure-role-profile:
         role_arn: "arn:aws:iam::378118068829:role/schemas-publisher"

      - run:
         name: aws s3 sync
         command: aws s3 sync --profile default --size-only ./schemas/ s3://schemas.dev.brightspace.com/feature-flags/

  deploy_npm:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout

      - run:
         name: npm login
         command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
         name: npm publish
         command: npm publish
